//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	timex "time"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSProvider) DeepCopyInto(out *AWSProvider) {
	*out = *in
	if in.AWSZoneType != nil {
		in, out := &in.AWSZoneType, &out.AWSZoneType
		*out = new(string)
		**out = **in
	}
	if in.AWSZoneTagFilter != nil {
		in, out := &in.AWSZoneTagFilter, &out.AWSZoneTagFilter
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AWSAssumeRole != nil {
		in, out := &in.AWSAssumeRole, &out.AWSAssumeRole
		*out = new(string)
		**out = **in
	}
	if in.AWSBatchChangeSize != nil {
		in, out := &in.AWSBatchChangeSize, &out.AWSBatchChangeSize
		*out = new(int)
		**out = **in
	}
	if in.AWSBatchChangeInterval != nil {
		in, out := &in.AWSBatchChangeInterval, &out.AWSBatchChangeInterval
		*out = new(timex.Duration)
		**out = **in
	}
	if in.AWSEvaluateTargetHealth != nil {
		in, out := &in.AWSEvaluateTargetHealth, &out.AWSEvaluateTargetHealth
		*out = new(bool)
		**out = **in
	}
	if in.AWSAPIRetries != nil {
		in, out := &in.AWSAPIRetries, &out.AWSAPIRetries
		*out = new(int)
		**out = **in
	}
	if in.AWSPreferCNAME != nil {
		in, out := &in.AWSPreferCNAME, &out.AWSPreferCNAME
		*out = new(bool)
		**out = **in
	}
	if in.AWSZoneCacheDuration != nil {
		in, out := &in.AWSZoneCacheDuration, &out.AWSZoneCacheDuration
		*out = new(timex.Duration)
		**out = **in
	}
	if in.AWSSDServiceCleanup != nil {
		in, out := &in.AWSSDServiceCleanup, &out.AWSSDServiceCleanup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSProvider.
func (in *AWSProvider) DeepCopy() *AWSProvider {
	if in == nil {
		return nil
	}
	out := new(AWSProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicInfo) DeepCopyInto(out *BasicInfo) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.AWSZone != nil {
		in, out := &in.AWSZone, &out.AWSZone
		*out = new(string)
		**out = **in
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(string)
		**out = **in
	}
	if in.TxtOwnerID != nil {
		in, out := &in.TxtOwnerID, &out.TxtOwnerID
		*out = new(string)
		**out = **in
	}
	if in.TxtPrefix != nil {
		in, out := &in.TxtPrefix, &out.TxtPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicInfo.
func (in *BasicInfo) DeepCopy() *BasicInfo {
	if in == nil {
		return nil
	}
	out := new(BasicInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareProvider) DeepCopyInto(out *CloudflareProvider) {
	*out = *in
	if in.CloudflareProxied != nil {
		in, out := &in.CloudflareProxied, &out.CloudflareProxied
		*out = new(bool)
		**out = **in
	}
	if in.CloudflareZonesPerPage != nil {
		in, out := &in.CloudflareZonesPerPage, &out.CloudflareZonesPerPage
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareProvider.
func (in *CloudflareProvider) DeepCopy() *CloudflareProvider {
	if in == nil {
		return nil
	}
	out := new(CloudflareProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Entry) DeepCopyInto(out *Entry) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = new(SourceInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(ProviderInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(RegistryInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Entry.
func (in *Entry) DeepCopy() *Entry {
	if in == nil {
		return nil
	}
	out := new(Entry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNS) DeepCopyInto(out *ExternalDNS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNS.
func (in *ExternalDNS) DeepCopy() *ExternalDNS {
	if in == nil {
		return nil
	}
	out := new(ExternalDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalDNS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSList) DeepCopyInto(out *ExternalDNSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalDNS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSList.
func (in *ExternalDNSList) DeepCopy() *ExternalDNSList {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalDNSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSSpec) DeepCopyInto(out *ExternalDNSSpec) {
	*out = *in
	if in.APIServerURL != nil {
		in, out := &in.APIServerURL, &out.APIServerURL
		*out = new(string)
		**out = **in
	}
	if in.Kubeconfig != nil {
		in, out := &in.Kubeconfig, &out.Kubeconfig
		*out = new(string)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = new([]Entry)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Entry, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSSpec.
func (in *ExternalDNSSpec) DeepCopy() *ExternalDNSSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNSStatus) DeepCopyInto(out *ExternalDNSStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNSStatus.
func (in *ExternalDNSStatus) DeepCopy() *ExternalDNSStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalDNSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderInfo) DeepCopyInto(out *ProviderInfo) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.DomainFilter != nil {
		in, out := &in.DomainFilter, &out.DomainFilter
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.ExcludeDomains != nil {
		in, out := &in.ExcludeDomains, &out.ExcludeDomains
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.ZoneIDFilter != nil {
		in, out := &in.ZoneIDFilter, &out.ZoneIDFilter
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Cloudflare != nil {
		in, out := &in.Cloudflare, &out.Cloudflare
		*out = new(CloudflareProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderInfo.
func (in *ProviderInfo) DeepCopy() *ProviderInfo {
	if in == nil {
		return nil
	}
	out := new(ProviderInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryInfo) DeepCopyInto(out *RegistryInfo) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.TXTOwnerID != nil {
		in, out := &in.TXTOwnerID, &out.TXTOwnerID
		*out = new(string)
		**out = **in
	}
	if in.TXTPrefix != nil {
		in, out := &in.TXTPrefix, &out.TXTPrefix
		*out = new(string)
		**out = **in
	}
	if in.TXTSuffix != nil {
		in, out := &in.TXTSuffix, &out.TXTSuffix
		*out = new(string)
		**out = **in
	}
	if in.TXTWildcardReplacement != nil {
		in, out := &in.TXTWildcardReplacement, &out.TXTWildcardReplacement
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryInfo.
func (in *RegistryInfo) DeepCopy() *RegistryInfo {
	if in == nil {
		return nil
	}
	out := new(RegistryInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceInfo) DeepCopyInto(out *SourceInfo) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.OCRouterName != nil {
		in, out := &in.OCRouterName, &out.OCRouterName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.AnnotationFilter != nil {
		in, out := &in.AnnotationFilter, &out.AnnotationFilter
		*out = new(string)
		**out = **in
	}
	if in.LabelFilter != nil {
		in, out := &in.LabelFilter, &out.LabelFilter
		*out = new(string)
		**out = **in
	}
	if in.FQDNTemplate != nil {
		in, out := &in.FQDNTemplate, &out.FQDNTemplate
		*out = new(string)
		**out = **in
	}
	if in.CombineFQDNAndAnnotation != nil {
		in, out := &in.CombineFQDNAndAnnotation, &out.CombineFQDNAndAnnotation
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreHostnameAnnotation != nil {
		in, out := &in.IgnoreHostnameAnnotation, &out.IgnoreHostnameAnnotation
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreIngressTLSSpec != nil {
		in, out := &in.IgnoreIngressTLSSpec, &out.IgnoreIngressTLSSpec
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreIngressRulesSpec != nil {
		in, out := &in.IgnoreIngressRulesSpec, &out.IgnoreIngressRulesSpec
		*out = new(bool)
		**out = **in
	}
	if in.GatewayNamespace != nil {
		in, out := &in.GatewayNamespace, &out.GatewayNamespace
		*out = new(string)
		**out = **in
	}
	if in.GatewayLabelFilter != nil {
		in, out := &in.GatewayLabelFilter, &out.GatewayLabelFilter
		*out = new(string)
		**out = **in
	}
	if in.Compatibility != nil {
		in, out := &in.Compatibility, &out.Compatibility
		*out = new(string)
		**out = **in
	}
	if in.PublishInternal != nil {
		in, out := &in.PublishInternal, &out.PublishInternal
		*out = new(bool)
		**out = **in
	}
	if in.PublishHostIP != nil {
		in, out := &in.PublishHostIP, &out.PublishHostIP
		*out = new(bool)
		**out = **in
	}
	if in.AlwaysPublishNotReadyAddresses != nil {
		in, out := &in.AlwaysPublishNotReadyAddresses, &out.AlwaysPublishNotReadyAddresses
		*out = new(bool)
		**out = **in
	}
	if in.ConnectorSourceServer != nil {
		in, out := &in.ConnectorSourceServer, &out.ConnectorSourceServer
		*out = new(string)
		**out = **in
	}
	if in.ServiceTypeFilter != nil {
		in, out := &in.ServiceTypeFilter, &out.ServiceTypeFilter
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.ManageDNSRecordTypes != nil {
		in, out := &in.ManageDNSRecordTypes, &out.ManageDNSRecordTypes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.DefaultTargets != nil {
		in, out := &in.DefaultTargets, &out.DefaultTargets
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceInfo.
func (in *SourceInfo) DeepCopy() *SourceInfo {
	if in == nil {
		return nil
	}
	out := new(SourceInfo)
	in.DeepCopyInto(out)
	return out
}
