---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - external-dns.appscode.com
  resources:
  - externaldns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-dns.appscode.com
  resources:
  - externaldns/finalizers
  verbs:
  - update
- apiGroups:
  - external-dns.appscode.com
  resources:
  - externaldns/status
  verbs:
  - get
  - patch
  - update
