apiVersion: external-dns.appscode.com/v1alpha1
kind: ExternalDNS
metadata:
  name: aws-edns-node
  namespace: demo
spec:
  source:
    type:
      group: ""
      version: v1
      kind: Node
    node:
      #annotationFilter: lke.linode.com/wgip=172.31.2.1
      fqdnTemplate: node.appscode.info
  registry: txt
  txtOwnerID: external-dns
  txtPrefix: xyz
  policy: sync
  provider: aws
  domainFilter:
      - appscode.info
  aws:
    zoneType: public
    secretRef:
      name: aws-credential
      credentialKey: credentials
