---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dep
  namespace: demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: demo-svc-lb
  namespace: demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: service.appscode.info #for Service, you have to add this annotation to specify fully qualified domain name
  labels:
    app: demo-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80