apiVersion: external-dns.appscode.com/v1alpha1
kind: ExternalDNS
metadata:
  name: edns
spec:
  source: service
  domain: superm4n.tk
  provider: aws
  policy: upsert-only
  aws_zone: public
  registry: txt
  txt_owner_id: external-dns
  txt_prefix: api