apiVersion: external-dns.appscode.com/v1alpha1
kind: ExternalDNS
metadata:
  name: edns
  namespace: demo
spec:
  entries:
    - sources:
        names:
          - service
      provider:
        name: aws
        domainFilter:
          - superm4n.tk
        aws:
          awsZoneType: public
      policy: upsert-only
      registry:
        type: txt
        txtOwnerID: external-dns
        txtPrefix: api
    - sources:
        names:
          - service
      provider:
        name: aws
        domainFilter:
          - superm4n.tk
        aws:
          awsZoneType: public
      policy: upsert-only
      registry:
        type: txt
        txtOwnerID: external-dns
        txtPrefix: demo