apiVersion: v1
stringData:
  CF_API_TOKEN: <cloudflare-api-token>
kind: Secret
metadata:
  name: cloudflare-credential
  namespace: demo #must be in the same namespace as External-DNS

#this secret name will be used in spec.cloudflare.secretRef.name

#and secret key in spec.cloudflare.secretRef.apiToken
#you can use api token otherwise api key and api email